#!/usr/bin/python3
def raise_exception():
    s = "hello"
    print("{:d}", format(s / 55555))
